"""
pdb_generator.py
----------------
Generates 3D atomic coordinate models (PDB format) for A-form siRNA double helices.
Encodes chemical modification identifiers into the crystallographic B-factor column
for 3Dmol.js highlighting and structural visualization.
"""

import math
from typing import Optional, Union, List


def mod_to_bfactor(mod_char: str) -> float:
    """Maps chemical modification names/codes to standardized PDB B-factors for 3Dmol.js styling."""
    c = (mod_char or '').upper()
    if any(k in c for k in ('2OME', 'METHYL', '2\'-OME', 'OMET')) or c == 'M': return 80.0 # 2'-O-Methyl (Amber Gold)
    if any(k in c for k in ('2F', 'FLUORO', '2\'-F')) or c == 'F': return 90.0  # 2'-Fluoro (Pink)
    if any(k in c for k in ('PS', 'PHOSPHOROTHIOATE', 'THIO')) or c in ('S', '1'): return 70.0  # Phosphorothioate (Emerald)
    if any(k in c for k in ('MOE', 'METHOXYETHYL')) or c == 'E': return 60.0  # 2'-MOE (Cyan)
    if any(k in c for k in ('LNA', 'LOCKED')) or c == 'L': return 50.0  # LNA (Purple)
    if any(k in c for k in ('DEOXY', 'DNA')) or c == 'D': return 85.0  # 2'-Deoxy (Blue)
    if any(k in c for k in ('UNA', 'UNLOCKED')) or c == '6': return 75.0
    if any(k in c for k in ('GNA', 'GLYCOL')) or c == '8': return 65.0
    if any(k in c for k in ('TNA', 'THREOSE')) or c == '9': return 55.0
    return 90.0


def generate_sirna_pdb(
    sense: str, 
    antisense: str, 
    parent_sense: Optional[str] = None, 
    parent_antisense: Optional[str] = None,
    mod_symbol: Optional[str] = None,
    mod_position: Optional[Union[int, str]] = None,
    mod_positions: Optional[Union[int, str]] = None,
    mod_strand: Optional[str] = None,
    sense_mods: Optional[str] = None,
    sense_positions: Optional[str] = None,
    antisense_mods: Optional[str] = None,
    antisense_positions: Optional[str] = None,
) -> str:
    """
    Generates a 3D PDB coordinate string for an A-form siRNA double helix with 100% continuous backbone topology.
    Emits standard RNA residue names (A, U, G, C) to guarantee unbroken 3Dmol.js cartoon rendering,
    and encodes modification types into the B-factor column (90.0=2'-F, 80.0=2'-OMe, 70.0=PS, 85.0=DNA, 60.0=MOE, 50.0=LNA).
    """
    def to_std_rna(seq: str) -> str:
        mod_map = {'F': 'U', 'M': 'U', 'S': 'U', 'D': 'C', 'E': 'U', 'L': 'A', '1': 'U'}
        return ''.join(c if c in 'AUGC' else mod_map.get(c, 'U') for c in seq.upper().replace('T', 'U'))

    p_sense = (parent_sense or to_std_rna(sense)).upper().replace("T", "U")
    p_anti  = (parent_antisense or to_std_rna(antisense)).upper().replace("T", "U")
    s_mod = sense.upper()
    a_mod = antisense.upper()
    
    pdb_lines = ["HEADER    SIRNA DUPLEX A-FORM HELIX 3D MODEL", "REMARK    GENERATED BY HELIXZERO-CMS BIOPHYSICS ENGINE"]
    atom_id = 1
    
    rise = 2.81              # 2.81 Angstroms rise per base pair
    twist_rad = 0.5708       # 32.7 degrees twist per base pair
    r_p = 9.8                # 9.8 A phosphate radius
    r_c4 = 8.2               # 8.2 A C4' radius
    r_c3 = 7.6               # 7.6 A C3' radius
    r_c1 = 6.2               # 6.2 A C1' radius
    r_base = 4.2             # 4.2 A nucleobase radius
    minor_groove_phase = 2.44 # 140 degrees minor groove phase shift

    # Build per-residue modification map
    s_bfactors = [0.0] * 21
    a_bfactors = [0.0] * 21

    # 1. Check sequence character deltas vs parent
    for i in range(min(len(s_mod), len(p_sense), 21)):
        if s_mod[i] in 'FMSEDL1' and s_mod[i] != p_sense[i]:
            s_bfactors[i] = mod_to_bfactor(s_mod[i])
    for i in range(min(len(a_mod), len(p_anti), 21)):
        if a_mod[i] in 'FMSEDL1' and a_mod[i] != p_anti[i]:
            a_bfactors[i] = mod_to_bfactor(a_mod[i])

    # 2. Check explicit modification parameters (handles single-mod AND multi-mod list strings)
    if mod_symbol and (mod_position or mod_positions):
        pos_str = str(mod_positions if mod_positions is not None else mod_position).replace('+', ',')
        sym_str = str(mod_symbol).replace('+', ',')
        strand_str = str(mod_strand or 'antisense').replace('+', ',')
        
        m_list = [m.strip() for m in sym_str.split(',') if m.strip()]
        p_list = [p.strip() for p in pos_str.split(',') if p.strip()]
        st_list = [s.strip().lower() for s in strand_str.split(',') if s.strip()]
        
        for idx, (m, p) in enumerate(zip(m_list, p_list)):
            try:
                p_idx = int(p) - 1
                if 0 <= p_idx < 21:
                    b_val = mod_to_bfactor(m)
                    cur_strand = st_list[idx] if idx < len(st_list) else (st_list[0] if st_list else 'antisense')
                    if 'sense' in cur_strand and 'anti' not in cur_strand:
                        s_bfactors[p_idx] = b_val
                    else:
                        a_bfactors[p_idx] = b_val
            except (ValueError, TypeError):
                pass

    # 3. Check explicit multi-mod parameters
    def apply_explicit_mods(mods_str, pos_str, target_b_arr):
        if not mods_str or not pos_str: return
        m_list = [m.strip() for m in str(mods_str).replace('+', ',').split(',') if m.strip()]
        p_list = [p.strip() for p in str(pos_str).replace('+', ',').split(',') if p.strip()]
        for m, p in zip(m_list, p_list):
            try:
                p_idx = int(p) - 1
                if 0 <= p_idx < 21:
                    target_b_arr[p_idx] = mod_to_bfactor(m)
            except (ValueError, TypeError):
                pass

    apply_explicit_mods(sense_mods, sense_positions, s_bfactors)
    apply_explicit_mods(antisense_mods, antisense_positions, a_bfactors)

    def get_std_base(parent_char: str) -> str:
        c = parent_char.upper()
        if c in ('A', 'U', 'G', 'C'): return f"  {c}"
        return "  A"

    def build_strand_atoms(parent_seq: str, chain_id: str, bfactor_list: list, is_antisense: bool = False):
        nonlocal atom_id
        for i in range(min(len(parent_seq), 21)):
            parent_char = parent_seq[i]
            res_name = get_std_base(parent_char)
            bfactor = bfactor_list[i]
            
            phase_offset = minor_groove_phase if is_antisense else 0.0
            angle = i * twist_rad + phase_offset
            z = i * rise
            
            # Backbone positions
            xp, yp     = r_p * math.cos(angle), r_p * math.sin(angle)
            xo5, yo5   = (r_p - 0.7) * math.cos(angle + 0.05), (r_p - 0.7) * math.sin(angle + 0.05)
            xc5, yc5   = (r_p - 1.3) * math.cos(angle + 0.10), (r_p - 1.3) * math.sin(angle + 0.10)
            xc4, yc4   = r_c4 * math.cos(angle + 0.15), r_c4 * math.sin(angle + 0.15)
            xo4, yo4   = (r_c4 - 0.9) * math.cos(angle + 0.25), (r_c4 - 0.9) * math.sin(angle + 0.25)
            xc3, yc3   = r_c3 * math.cos(angle + 0.18), r_c3 * math.sin(angle + 0.18)
            xo3, yo3   = (r_c3 + 1.2) * math.cos(angle + 0.22), (r_c3 + 1.2) * math.sin(angle + 0.22)
            xc2, yc2   = (r_c3 - 0.8) * math.cos(angle + 0.32), (r_c3 - 0.8) * math.sin(angle + 0.32)
            xc1, yc1   = r_c1 * math.cos(angle + 0.35), r_c1 * math.sin(angle + 0.35)
            xbase, ybase = r_base * math.cos(angle + 0.45), r_base * math.sin(angle + 0.45)
            
            res_num = i + 1
            
            pdb_lines.append(f"ATOM  {atom_id:5d}  P   {res_name:3s} {chain_id}{res_num:4d}    {xp:8.3f}{yp:8.3f}{z:8.3f}  1.00{bfactor:6.2f}           P")
            atom_id += 1
            pdb_lines.append(f"ATOM  {atom_id:5d}  OP1 {res_name:3s} {chain_id}{res_num:4d}    {xp+0.9:8.3f}{yp+0.9:8.3f}{z+0.5:8.3f}  1.00{bfactor:6.2f}           O")
            atom_id += 1
            pdb_lines.append(f"ATOM  {atom_id:5d}  OP2 {res_name:3s} {chain_id}{res_num:4d}    {xp-0.9:8.3f}{yp-0.9:8.3f}{z-0.5:8.3f}  1.00{bfactor:6.2f}           O")
            atom_id += 1
            pdb_lines.append(f"ATOM  {atom_id:5d}  O5' {res_name:3s} {chain_id}{res_num:4d}    {xo5:8.3f}{yo5:8.3f}{z+0.6:8.3f}  1.00{bfactor:6.2f}           O")
            atom_id += 1
            pdb_lines.append(f"ATOM  {atom_id:5d}  C5' {res_name:3s} {chain_id}{res_num:4d}    {xc5:8.3f}{yc5:8.3f}{z+1.1:8.3f}  1.00{bfactor:6.2f}           C")
            atom_id += 1
            pdb_lines.append(f"ATOM  {atom_id:5d}  C4' {res_name:3s} {chain_id}{res_num:4d}    {xc4:8.3f}{yc4:8.3f}{z+1.4:8.3f}  1.00{bfactor:6.2f}           C")
            atom_id += 1
            pdb_lines.append(f"ATOM  {atom_id:5d}  O4' {res_name:3s} {chain_id}{res_num:4d}    {xo4:8.3f}{yo4:8.3f}{z+1.6:8.3f}  1.00{bfactor:6.2f}           O")
            atom_id += 1
            pdb_lines.append(f"ATOM  {atom_id:5d}  C3' {res_name:3s} {chain_id}{res_num:4d}    {xc3:8.3f}{yc3:8.3f}{z+2.1:8.3f}  1.00{bfactor:6.2f}           C")
            atom_id += 1
            pdb_lines.append(f"ATOM  {atom_id:5d}  O3' {res_name:3s} {chain_id}{res_num:4d}    {xo3:8.3f}{yo3:8.3f}{z+2.7:8.3f}  1.00{bfactor:6.2f}           O")
            atom_id += 1
            pdb_lines.append(f"ATOM  {atom_id:5d}  C2' {res_name:3s} {chain_id}{res_num:4d}    {xc2:8.3f}{yc2:8.3f}{z+1.9:8.3f}  1.00{bfactor:6.2f}           C")
            atom_id += 1
            pdb_lines.append(f"ATOM  {atom_id:5d}  C1' {res_name:3s} {chain_id}{res_num:4d}    {xc1:8.3f}{yc1:8.3f}{z+1.2:8.3f}  1.00{bfactor:6.2f}           C")
            atom_id += 1
            pdb_lines.append(f"ATOM  {atom_id:5d}  N1  {res_name:3s} {chain_id}{res_num:4d}    {xbase:8.3f}{ybase:8.3f}{z+0.8:8.3f}  1.00{bfactor:6.2f}           N")
            atom_id += 1

    build_strand_atoms(p_sense, 'A', s_bfactors, is_antisense=False)
    build_strand_atoms(p_anti, 'B', a_bfactors, is_antisense=True)
    
    pdb_lines.append("END")
    return "\n".join(pdb_lines)
