import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from src import predictor, modification_engine

sense = 'AAGGCCUUUCACUACUCCUAC'
anti = 'GUAGGAGUAGUGAAAGGCCUU'

print('=== MEG-MOD PAPER CASE STUDY VALIDATION ===')
print(f'Sense (5->3):     {sense}')
print(f'Antisense (5->3): {anti}\n')

# 1. Single Mod Scan
single_res = predictor.predict_modified(sense, anti, mode='scan', model_key='Ensemble_v4')

print(f"Parent Baseline Score: {single_res['parent_score']:.2f}%")

top_as = [r for r in single_res['results'] if getattr(r, 'mod_strand', '') == 'antisense'][:6]
print('\nTop Antisense Modification Positions (Predicted by local Ensemble_v4 model):')
for r in top_as:
    print(f"  AS Pos {r.mod_position} ({r.mod_symbol}): Score {r.efficacy_score:.2f}% (Delta +{r.delta_score:.2f}%)")

top_ss = [r for r in single_res['results'] if getattr(r, 'mod_strand', '') == 'sense'][:6]
print('\nTop Sense Modification Positions (Predicted by local Ensemble_v4 model):')
for r in top_ss:
    print(f"  Sense Pos {r.mod_position} ({r.mod_symbol}): Score {r.efficacy_score:.2f}% (Delta +{r.delta_score:.2f}%)")

# 2. Multi-Mod Beam Search
print('\n=== Multi-Mod Beam Search Results ===')
proxy_singles = [modification_engine.CmSiRNA(
    sense=sense, antisense=anti, mod_symbol=r.mod_symbol, mod_position=r.mod_position,
    mod_strand=r.mod_strand, parent_sense=sense, parent_antisense=anti, efficacy_score=r.efficacy_score
) for r in single_res['results']]

mm_variants = modification_engine.multi_mod_scan(
    sense, anti, max_mods=5, beam_width=20, model_key='Ensemble_v4', single_results=proxy_singles, parent_score=single_res['parent_score']
)
print(f"Generated {len(mm_variants)} multi-mod candidates via beam search.")

# Display top multi-mod candidates generated by beam search
print("\nTop 5 Multi-Mod Combinations Generated by Beam Search:")
for i, v in enumerate(mm_variants[:5], 1):
    print(f"Design {i}: Positions [{v.mod_positions}] Symbols [{v.mod_symbol}] Score {v.efficacy_score:.2f}% (Delta +{v.delta_score:.2f}%)")
    print(f"  Sense: {v.sense}")
    print(f"  Anti:  {v.antisense}")
