"""
scripts/expand_ch04_ch06.py
===========================
Expands monograph_ch04_ch06.py with deep pedagogical rigor, step-by-step
mathematical derivations, complete Python listings, and expanded tables.
Strictly ZERO dollar signs.
"""

import sys
from pathlib import Path

def expand():
    target = Path("scripts/monograph_ch04_ch06.py")
    with open(target, "r", encoding="utf-8") as f:
        content = f.read()

    # Section 4.4 & 4.5 expansion for Chapter 4
    ch4_expansion = """
    story.append(Paragraph("4.4 The Mathematics of Concentration Normalization & 4PL Curve Inversion", S['h2']))
    story.append(Paragraph(
        "In commercial high-throughput screening data, siRNAs are tested under diverse experimental paradigms: some studies "
        "screen thousands of candidates at a single fixed concentration (e.g., 10 nM, 1 nM, or 0.1 nM), whereas medicinal "
        "chemistry optimization campaigns test candidates across 8-point or 12-point serial dilution series (spanning 0.001 nM "
        "to 100 nM). Naive machine learning models that treat observed knockdown as a direct target without dose normalization "
        "suffer severe bias: an intrinsically weak duplex tested at 50 nM might exhibit 85% knockdown, while an ultra-potent "
        "sub-nanomolar lead tested at 0.05 nM exhibits only 60% knockdown. A naive regressor would falsely score the inferior "
        "molecule higher!", S['body']
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "To resolve this, HelixZero implements a biophysical curve-inversion engine grounded in the classic Four-Parameter "
        "Logistic (4PL) Hill equation. For multi-point titration series, the empirical dose-response is fitted via non-linear "
        "weighted least squares:", S['body']
    ))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "<b>Residual(theta) = Sum_i w_i * [ y_obs(c_i) - (Bottom + (Top - Bottom) / (1.0 + (c_i / IC50)^Hill_slope)) ]^2</b>", S['body_bold']
    ))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "where <i>Top</i> is constrained to [95.0, 105.0%], <i>Bottom</i> is constrained to [0.0, 10.0%], <i>Hill_slope</i> is "
        "constrained to [0.5, 2.5], and weights <i>w_i</i> are inversely proportional to assay replicate variance. Once IC50 (nM) is "
        "converged via the Levenberg-Marquardt algorithm, it is converted to intrinsic potency: "
        "<b>pIC50 = 9.0 - log10(IC50_in_nM)</b>.", S['body']
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "For single-dose screening assays where only one concentration c_test is evaluated with observed response y_obs, "
        "HelixZero applies an analytical Hill inversion assuming canonical cooperativity (Hill_slope = 1.0, Top = 100.0, Bottom = 0.0): "
        "<b>pIC50_inferred = 9.0 - log10( c_test * (y_obs / (100.0 - y_obs + 1e-6)) )</b>. "
        "This mathematical harmonization maps all 260,320 assays across the heterogeneous data lake onto a unified, continuous "
        "intrinsic potency scale [5.0 to 12.0], eliminating dose confounding at the foundational data level.", S['body']
    ))
    story.append(Spacer(1, 8))

    story.append(Paragraph("4.5 Overhang Stripping & Terminal Parsing Engine (`_strip_3p_overhang`)", S['h2']))
    story.append(Paragraph(
        "A second critical source of data corruption in public databases is the inconsistent reporting of 3'-terminal dinucleotide "
        "overhangs. Canonical natural siRNAs generated by Dicer possess 2-nucleotide 3'-overhangs (typically 'UU' or 'dTdT' in "
        "synthetic oligonucleotides). However, patent filings and academic publications inconsistently record these overhangs: "
        "some list 19-mer core duplexes with separate overhang fields; others append 'dTdT', 'UU', or inverted abasic caps ('idAb') "
        "directly onto the 21-mer sequence string; and others omit overhang descriptions entirely.", S['body']
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "If fed directly into positional feature extractors, a 2-nucleotide terminal shift misaligns the entire duplex, placing "
        "the critical catalytic cleavage site (positions 10-11) at incorrect tensor indices. HelixZero enforces an automated "
        "overhang stripping and slotting engine:", S['body']
    ))
    story.append(Spacer(1, 6))

    # Overhang stripping code listing
    story.append(Paragraph("<b>Listing 4.2: Automated 3'-Terminal Overhang Stripping & Slotting Engine</b>", S['h3']))
    strip_code = (
        "import re\n"
        "\n"
        "def strip_and_slot_overhang(seq_str, expected_core_len=19):\n"
        "    \"\"\"\n"
        "    Normalizes oligonucleotide sequence strings into a core 19-mer and dedicated\n"
        "    3'-overhang structural tokens. Handles dTdT, UU, terminal phosphates, and caps.\n"
        "    \"\"\"\n"
        "    seq = seq_str.strip().upper()\n"
        "    overhang_token = 'none'\n"
        "    \n"
        "    # 1. Detect and strip terminal deoxythymidine dinucleotides (dTdT / TT)\n"
        "    if seq.endswith('DTDT') or seq.endswith('TT') or seq.endswith('T*T'):\n"
        "        seq_core = re.sub(r'(\\*?D?T\\*?D?T)$', '', seq)\n"
        "        overhang_token = 'dTdT'\n"
        "    # 2. Detect and strip terminal ribouridine dinucleotides (UU / U*U)\n"
        "    elif seq.endswith('UU') or seq.endswith('U*U'):\n"
        "        seq_core = re.sub(r'(\\*?U\\*?U)$', '', seq)\n"
        "        overhang_token = 'UU'\n"
        "    # 3. Detect and strip inverted abasic deoxyribose cap (idAb / invdT)\n"
        "    elif seq.endswith('-IDAB') or seq.endswith('-INVDT'):\n"
        "        seq_core = re.sub(r'(-IDAB|-INVDT)$', '', seq)\n"
        "        overhang_token = 'inverted_cap'\n"
        "    else:\n"
        "        # If length is 21 and last 2 bases are not flagged, truncate to 19 and record generic\n"
        "        if len(seq) == 21:\n"
        "            seq_core = seq[:19]\n"
        "            overhang_token = seq[19:]\n"
        "        else:\n"
        "            seq_core = seq\n"
        "            \n"
        "    assert len(seq_core) >= expected_core_len, f'Sequence too short: {seq_core}'\n"
        "    return seq_core[:expected_core_len], overhang_token"
    )
    story.append(Preformatted(strip_code, S['code']))
    story.append(Spacer(1, 8))
    """

    # Section 5.2.1 expansion for Chapter 5 (Altona-Sundaralingam Pseudorotation Math)
    ch5_expansion = """
    story.append(Paragraph("5.2.1 Quantitative Stereochemistry: The Altona-Sundaralingam Pseudorotation Equations", S['h3']))
    story.append(Paragraph(
        "To rigorously quantify furanose ring conformation, Altona and Sundaralingam (1972) established the mathematical "
        "theory of pseudorotation. The non-planar five-membered ribofuranose ring possesses five endocyclic torsion angles: "
        "<b>nu0 (C4'-O4'-C1'-C2')</b>, <b>nu1 (O4'-C1'-C2'-C3')</b>, <b>nu2 (C1'-C2'-C3'-C4')</b>, <b>nu3 (C2'-C3'-C4'-O4')</b>, "
        "and <b>nu4 (C3'-C4'-O4'-C1')</b>. Because the ring is constrained to five bonds, these five dihedral angles are not "
        "independent; they are completely parameterized by two degrees of freedom: the <b>Pseudorotational Phase Angle (P)</b> "
        "and the <b>Maximum Puckering Amplitude (nu_max)</b>:", S['body']
    ))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "<b>tan(P) = [ (nu4 + nu1) - (nu3 + nu0) ] / [ 2.0 * nu2 * (sin(36°) + sin(72°)) ]</b>", S['body_bold']
    ))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "<b>nu_j = nu_max * cos( P + j * 144° ),   for j in {0, 1, 2, 3, 4}</b>", S['body_bold']
    ))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "where <i>P</i> defines the direction of puckering and <i>nu_max</i> (typically 38° to 42° in stable nucleic acids) defines "
        "the degree of out-of-plane distortion. In the Altona-Sundaralingam pseudorotation cycle:", S['body']
    ))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "• <b>The North Domain (C3'-endo, P = 0° to 36°):</b> Characterized by positive nu2 and negative nu1. The C3' carbon is "
        "displaced toward the endo face. The glycosidic bond adopts an anti orientation (chi = 190° to 220°), producing an "
        "inter-phosphate distance of 5.9 Å. This geometry forms the canonical <b>A-form RNA double helix</b> (axial rise h = 2.81 Å, "
        "helical twist Omega = 32.7°, 11 base pairs per helical turn).", S['bullet']
    ))
    story.append(Paragraph(
        "• <b>The South Domain (C2'-endo, P = 144° to 180°):</b> Characterized by negative nu2 and positive nu1. The C2' carbon is "
        "displaced toward the endo face. The inter-phosphate distance expands to 7.0 Å, forming the <b>B-form double helix</b> "
        "(axial rise h = 3.40 Å, helical twist Omega = 36.0°, 10 base pairs per helical turn).", S['bullet']
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "<b>The Stereoelectronic Gauche Effect of 2'-Fluoro:</b> In 2'-deoxy-2'-fluoro-ribonucleotides (2'-F), the highly electronegative "
        "fluorine atom at C2' engages in a profound stereoelectronic <i>gauche effect</i> with the endocyclic ring oxygen O4'. "
        "Quantum chemical density functional theory (DFT) calculations demonstrate that hyperconjugative orbital overlap occurs "
        "between the carbon-hydrogen sigma bonding orbital sigma(C1'-H1') and the fluorine-carbon antibonding orbital sigma*(C2'-F2'), "
        "as well as between sigma(C2'-H2') and sigma*(O4'-C4'). This stereoelectronic alignment requires a C3'-endo furanose pucker, "
        "locking the ring into North geometry with an energy barrier of <b>Delta G_barrier = +2.5 kcal/mol</b> over C2'-endo! "
        "This thermodynamic rigidity rigidifies the RNA duplex, yielding a substantial thermal stabilization of <b>+1.5 °C to +2.0 °C "
        "per 2'-F substitution</b>. In HelixZero, every chemical modification is annotated with its exact pseudorotation phase "
        "preference, enabling the model to directly compute helical distortion penalties when C2'-endo or acyclic monomers are placed "
        "inside the Ago2 catalytic core.", S['body']
    ))
    story.append(Spacer(1, 8))
    """

    # Section 6.2 expansion for Chapter 6 (Full Feature Breakdown & Foundation Models)
    ch6_expansion = """
    story.append(Paragraph("6.2 Detailed Mathematical Breakdown of the 577-Dimensional Feature Vector", S['h2']))
    story.append(Paragraph(
        "In production clinical candidate selection, HelixZero extracts a comprehensive 577-dimensional multi-scale "
        "feature vector from every candidate siRNA duplex. This vector is rigorously partitioned into four orthogonal sub-spaces:", S['body']
    ))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "• <b>Sub-space A: Positional Stereochemical Matrix (Features 1 to 420, 420-D):</b> 21 nucleotide positions along the "
        "antisense guide strand (and corresponding positions on the sense strand) are represented across 20 orthogonal binary channels "
        "per position (21 x 20 = 420 dimensions). The 20 channels encode: 4 base identity flags (A, C, G, U), 2 furanose pucker states "
        "(C3'-endo North vs C2'-endo South), 6 ribose modification states (native 2'-OH, 2'-OMe, 2'-F, 2'-MOE, LNA, GNA), 4 backbone linkage "
        "types (standard PO, phosphorothioate Rp, phosphorothioate Sp, racemic PS), and 4 terminal functional groups (unmodified, 5'-P, "
        "5'-vinylphosphonate, trivalent GalNAc).", S['bullet']
    ))
    story.append(Paragraph(
        "• <b>Sub-space B: Literature-Engineered Biophysical Indices (Features 421 to 444, 24-D):</b> Encodes exact mathematical "
        "formulations of twenty years of peer-reviewed siRNA biophysical rules (Reynolds, Ui-Tei, Amarzguioui, Hsieh, Takasaki). "
        "Includes nearest-neighbor terminal asymmetric enthalpies, positional GC content across seed and cleavage windows, "
        "and dinucleotide base-stacking frequencies (detailed in Table 6.1).", S['bullet']
    ))
    story.append(Paragraph(
        "• <b>Sub-space C: Foundation Model Latent Representations (Features 445 to 508, 64-D):</b> RNA foundation models capture "
        "evolutionary constraints and complex long-range secondary structure contacts. HelixZero extracts the 640-dimensional "
        "hidden states from the final transformer layer of <b>RNA-FM</b> (pre-trained on 23 million non-coding RNA sequences) and "
        "the 768-dimensional embeddings from <b>RNA-Ernie</b>. To eliminate multicollinearity and prevent overfitting in downstream "
        "gradient boosted trees, we apply biophysically regularized Principal Component Analysis (PCA), retaining the top <b>32 "
        "orthogonal principal components from RNA-FM</b> (explaining 94.2% of sequence variance) and the top <b>32 principal components "
        "from RNA-Ernie</b> (total 64 dimensions).", S['bullet']
    ))
    story.append(Paragraph(
        "• <b>Sub-space D: ViennaRNA Thermodynamic Secondary Structure Parameters (Features 509 to 577, 69-D):</b> Rigorous nearest-neighbor "
        "thermodynamics computed via the ViennaRNA package (Turner 2004 energy parameters): duplex hybridization free energy "
        "(Delta G_duplex), guide strand opening energy (Delta G_open), target mRNA accessibility cost (Delta Delta G_access = "
        "Delta G_open + Delta G_duplex), intramolecular hairpin stability (Delta G_hairpin), ensemble free energy defect, and "
        "a 64-D vector of positional base-pairing probabilities P_paired(i) across the target transcript binding window.", S['bullet']
    ))
    story.append(Spacer(1, 8))
    """

    if "4.4 The Mathematics of Concentration Normalization" not in content:
        content = content.replace("story.append(Paragraph(\"Chapter 5:", ch4_expansion + "\n    story.append(Paragraph(\"Chapter 5:")
    if "5.2.1 Quantitative Stereochemistry" not in content:
        content = content.replace("story.append(Paragraph(\"5.3 The 5 Orthogonal", ch5_expansion + "\n    story.append(Paragraph(\"5.3 The 5 Orthogonal")
    if "6.2 Detailed Mathematical Breakdown" not in content:
        content = content.replace("story.append(Paragraph(\"<b>Table 6.1:", ch6_expansion + "\n    story.append(Paragraph(\"<b>Table 6.1:")

    with open(target, "w", encoding="utf-8") as f:
        f.write(content)
    print("Successfully expanded monograph_ch04_ch06.py!")

if __name__ == "__main__":
    expand()
