"""
scripts/test_pipeline_integrity.py
==================================
Tests core platform capabilities before model migration:
1. Single-mod scan & scoring
2. Multi-mod generation & ESC+ candidate generation
3. Specific custom variant prediction (e.g. Inclisiran chemistry)
4. 3D PDB structure generation & continuous cartoon topology validation
5. Biophysics penalties & thermodynamics
"""

import sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from smepred.src.modification_engine import single_mod_scan, multimod_gen
from smepred.src.multislot_designer import generate_esc_plus_candidates, rank_esc_plus_designs
from smepred.src.predictor import predict_modified, extract_structural_properties, get_prediction_engine
from smepred.src.pdb_generator import generate_sirna_pdb
from smepred.src.biophysics import calculate_adjusted_efficacy

def test_single_mod_scan():
    print("[1/5] Testing Single Modification Scan...")
    s = "CUACGAGACUGAUGACUAUTT"
    a = "AUAGUCAUCAGUCUCGUAGTT"
    variants = single_mod_scan(s, a)
    assert len(variants) > 0, "No variants generated by single_mod_scan"
    print(f"      Generated {len(variants)} single-mod variants successfully.")
    
    # Test predict_modified scan mode
    res = predict_modified(s, a, mode="scan", conc_nM=10.0)
    assert "results" in res and len(res["results"]) > 0, "predict_modified scan returned empty results"
    top1 = res["results"][0]
    print(f"      Top single-mod: {top1.mod_symbol} at pos {top1.mod_position} ({top1.mod_strand}), "
          f"Efficacy={top1.efficacy_score:.2f}%, delta={top1.delta_score:+.2f}%")
    return True

def test_multimod():
    print("[2/5] Testing Multi-Mod Generation & ESC+ Designs...")
    s = "CUACGAGACUGAUGACUAUTT"
    a = "AUAGUCAUCAGUCUCGUAGTT"
    v = multimod_gen(s, a, sense_mods="M,M,F,F", sense_positions="1,2,3,4",
                     antisense_mods="M,M,F,F", antisense_positions="1,2,3,4")
    assert v is not None, "multimod_gen returned None"
    print(f"      multimod_gen variant created: sense={v.sense[:8]}... anti={v.antisense[:8]}...")
    
    # Test ESC+ multi-slot candidate generation
    esc_designs = rank_esc_plus_designs(s, a)
    assert len(esc_designs) == 16, f"Expected 16 ESC+ designs, got {len(esc_designs)}"
    top_esc = esc_designs[0]
    print(f"      Top ESC+ design: '{top_esc.label}', raw={top_esc.raw_score:.2f}%, adj={top_esc.adjusted_score:.2f}%")
    return True

def test_predict_specific_variant():
    print("[3/5] Testing Specific Variant Prediction...")
    engine = get_prediction_engine()
    s = "CUACGAGACUGAUGACUAUTT"
    a = "AUAGUCAUCAGUCUCGUAGTT"
    # Specific custom variant with 2'-OMe and 2'-F
    res = engine.predict_variant(
        sense=s,
        antisense=a,
        sense_mods="F,M,F,M",
        mod_positions=[1, 2, 3, 4],
    )
    assert "results" in res and len(res["results"]) > 0, "predict_variant returned empty results"
    cand = res["results"][0]
    print(f"      Custom variant predicted: Efficacy={cand.efficacy_score:.2f}%, "
          f"pIC50={cand.estimated_pIC50}, IC50={cand.estimated_IC50_nM} nM, Tox={cand.toxicity_label}")
    return True

def test_3d_structure():
    print("[4/5] Testing 3D PDB Structure Generation...")
    s = "CUACGAGACUGAUGACUAUTT"
    a = "AUAGUCAUCAGUCUCGUAGTT"
    pdb_str = generate_sirna_pdb(s, a, mod_symbol="M,F", mod_positions="1,2", mod_strand="sense")
    assert pdb_str.startswith("HEADER"), "PDB missing HEADER"
    assert "ATOM" in pdb_str, "PDB missing ATOM records"
    lines = [line for line in pdb_str.splitlines() if line.startswith("ATOM")]
    print(f"      PDB generated successfully with {len(lines)} atoms across both strands.")
    
    # Test structural properties dict
    props = extract_structural_properties(s, a, mod_symbol="M", mod_position=1, mod_strand="sense")
    assert "duplex_mfe_kcal" in props, "Structural properties missing duplex_mfe_kcal"
    assert "pdb_data" in props and len(props["pdb_data"]) > 0, "Structural properties missing pdb_data"
    print(f"      Duplex MFE: {props['duplex_mfe_kcal']} kcal/mol, delta_duplex_dg: {props['delta_duplex_dg']} kcal/mol")
    return True

def test_biophysics():
    print("[5/5] Testing Biophysics Penalty Calculations...")
    s = "CUACGAGACUGAUGACUAUTT"
    a = "AUAGUCAUCAGUCUCGUAGTT"
    raw_score = 85.0
    adj_score, penalties, notes = calculate_adjusted_efficacy(raw_score, s, a, s, a)
    assert adj_score is not None, "calculate_adjusted_efficacy failed"
    print(f"      Raw={raw_score:.2f}% -> Adjusted={adj_score:.2f}% (Penalties: {penalties})")
    return True

if __name__ == "__main__":
    print("=" * 70)
    print("RUNNING PLATFORM INTEGRITY VERIFICATION SUITE")
    print("=" * 70)
    test_single_mod_scan()
    test_multimod()
    test_predict_specific_variant()
    test_3d_structure()
    test_biophysics()
    print("=" * 70)
    print("ALL 5 CORE CAPABILITIES VERIFIED SUCCESSFULLY!")
    print("=" * 70)
